include:
  - component: "${CI_SERVER_FQDN}/sndi-lille/ressources-communes/components/meta-component-java-kube/meta-components@2.0.0"
    inputs:
      sonar_token: ${SONAR_KEY}
      sonar_project_key: ${SONAR_PROJECT_KEY}
      sonar_props_java: >
        -Dsonar.coverage.exclusions=src/test/java/**
        -Dsonar.java.binaries=target/classes
        -Dsonar.java.coveragePlugin=jacoco
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        -Dsonar.exclusions=**/test/**,**/*Test*.java,**/*Tests*.java,**/*TestCase*.java
        -Dsonar.junit.reportPaths=target/surefire-reports/*.xml
      maven_java_version: 25
      maven_build_args_opts: -Drevision=${CLEANED_TAG_AND_VERSION_NAME}
      trivy_path_to_trivyignore: "${CI_PROJECT_DIR}/.trivyignore"
  - project: 'ressources-humaines/outils/ci-templates'
    ref: main
    file:
      - '/templates/workflow.yaml'
      - 'templates/formatting.yaml'
      - 'templates/build-test.yaml'
      - '/templates/quality.yaml'
      - '/templates/pages.yaml'
      - '/templates/kube/docker.yaml'
      - '/templates/kube/deploy.yaml'


stages:
  - check-source-branch
  - security-app
  - build-app-and-test
  - quality
  - calculate-version-and-release
  - tag
  - prepare-docker
  - trigger-docker
  - docker
  - release-gitops


release-gitops-dev1:
  stage: release-gitops
  extends: .template:gitops-updater
  variables:
    REPO: "https://gitlab.insee.fr/dsi/Compas/CompasGitops.git"
    BRANCH: "master"
    PATH_TO_VALUE: "apps/compas-api-dev1/values.yaml"
    KEY_TO_CHANGE: "api-appli-compas.image.tag"
    NEW_VALUE: "${CLEANED_TAG_AND_VERSION_NAME}"
    USERNAME: "${GITOPS_USERNAME}"
    PASSWORD_VAR: "${GITOPS_TOKEN}"
    AUTOMERGE: "true"

  rules:
    - when: manual

release-gitops-dev2:
  stage: release-gitops
  extends: .template:gitops-updater
  variables:
    REPO: "https://gitlab.insee.fr/dsi/Compas/CompasGitops.git"
    BRANCH: "master"
    PATH_TO_VALUE: "apps/compas-api-dev2/values.yaml"
    KEY_TO_CHANGE: "api-appli-compas.image.tag"
    NEW_VALUE: "${CLEANED_TAG_AND_VERSION_NAME}"
    USERNAME: "${GITOPS_USERNAME}"
    PASSWORD_VAR: "${GITOPS_TOKEN}"
    AUTOMERGE: "true"
  rules:
    - when: manual

release-gitops-dev3:
  stage: release-gitops
  extends: .template:gitops-updater
  variables:
    REPO: "https://gitlab.insee.fr/dsi/Compas/CompasGitops.git"
    BRANCH: "master"
    PATH_TO_VALUE: "apps/compas-api-dev3/values.yaml"
    KEY_TO_CHANGE: "api-appli-compas.image.tag"
    NEW_VALUE: "${CLEANED_TAG_AND_VERSION_NAME}"
    USERNAME: "${GITOPS_USERNAME}"
    PASSWORD_VAR: "${GITOPS_TOKEN}"
    AUTOMERGE: "true"
  rules:
    - when: manual



release-gitops-prod:
  stage: release-gitops
  extends: .template:gitops-updater
  variables:
    REPO: "https://gitlab.insee.fr/dsi/Compas/Compas-gitops-production.git"
    BRANCH: "main"
    PATH_TO_VALUE: "apps/compas-api/values.yaml"
    KEY_TO_CHANGE: "api-appli-compas.image.tag"
    NEW_VALUE: "${NEXT_TAG}"
    USERNAME: "${GITOPS_USERNAME_PROD}"
    PASSWORD_VAR: "${GITOP_TOKEN_PROD_TAG}"
    AUTOMERGE: "true"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: manual