# Var env pour l'URL de bdd
# jdbc:postgresql://dvcompaslg001.ad.insee.intra:1983/di_pg_compas_dv01?currentSchema=compas_dev5
spring.datasource.url=${COMPAS_SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (fourni par Spring Data JPA)
spring.jpa.hibernate.ddl-auto=update

# Configuration OpenFeign
spring.cloud.openfeign.client.config.oscar-service.url=https://api-referentiel-applications.developpement.insee.fr/
oscar.url=https://api-referentiel-applications.developpement.insee.fr/
spring.cloud.openfeign.oauth2.clientRegistrationId=keycloak
spring.cloud.openfeign.oauth2.enabled=true

# Configuration Keycloak
compas.web.springdoc.token-url=${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
keycloak.auth-server-url=https://auth.insee.test/auth
keycloak.realm=agents-insee-interne
compas.service.keycloak.client=compas-service
compas.service.keycloak.authorization-grant-type=client_credentials
compas.service.keycloak.credentials.secret=${COMPAS_SERVICE_KEYCLOAK_CREDENTIALS_SECRET}
api.analyzer.base-url=https://api-analyzer.developpement.insee.fr
apirh.base-url=https://apirh-interne.developpement2.insee.fr/agents

# Type d'authentification pour Oscar
oscar.client.authType=keycloak

springdoc.swagger-ui.use-root-path=true
springdoc.swagger-ui.oauth.clientId=localhost-frontend-minimal

fr.insee.compas.proxy.name=proxy-rie.http.insee.fr
fr.insee.compas.proxy.port=8080
fr.insee.compas.proxy.non-proxy-hosts=localhost,127.0.0.1,.insee.fr,.insee.eu,.insee.test,.insee.intra


fr.insee.compas.score.application.conso-max= 1500
fr.insee.compas.score.application.pression-max-ram= 1500
fr.insee.compas.score.application.pression-max-cpu= 1500000
fr.insee.compas.score.application.pression-max-disk= 18000

fr.insee.compas.score.module.conso-max= 750
fr.insee.compas.score.module.pression-max-ram= 800
fr.insee.compas.score.module.pression-max-cpu= 900000
fr.insee.compas.score.module.pression-max-disk= 4000


fr.insee.compas.score.application.conso-facteur-utilisation = 0.6
fr.insee.compas.score.module.conso-facteur-utilisation = 0.6

spoc.username=appli_COMPAS
spoc.url=https://api-spoc-envoi.recette.insee.fr/send
sender.mail=noreply-compas@insee.fr
default.receiver.mail=colin.despouys@insee.fr, philippe.clement@insee.fr
receiver.mail.add.balf.oscar=FALSE
mail.cve.alert.severity=CRITICAL,HIGH