# Var env pour l'URL de bdd
# jdbc:postgresql://dvcompaslg001.ad.insee.intra:1983/di_pg_compas_dv01?currentSchema=compas_devX
spring.datasource.url= ${COMPAS_SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate (fournit par Spring Data JPA)
spring.jpa.hibernate.ddl-auto=none

spring.cloud.openfeign.client.config.oscar-service.url = https://api-oscar-gestion.insee.fr/
logging.level.feign=DEBUG

