
spring.datasource.username=VAULT[ut/compas/dv/db/dvcompaslg001/user/login,data]
spring.datasource.password=VAULT[ut/compas/dv/db/dvcompaslg001/user/password,data]
oscar4.service.keycloak.credentials.secret=VAULT[ut/oscar/service/keycloak,client_secret]

fr.insee.compas.gitlab.token=VAULT[ut/compas/service/keycloak, client_secret]



