
spring.datasource.username=VAULT[ut/compas/dv/db/dvcompaslg001/user_loc/login,data]
spring.datasource.password=VAULT[ut/compas/dv/db/dvcompaslg001/user_loc/password,data]
compas.service.keycloak.credentials.secret=VAULT[ut/compas/service/keycloak,client_secret]

fr.insee.compas.gitlab.token=VAULT[ut/compas/equipe/dev_ut-compas,gitlab_token]
fr.insee.compas.sonar.token=VAULT[ut/compas/equipe/dev_ut-compas,sonar_token]
fr.insee.compas.github.sonar.token=VAULT[ut/compas/equipe/dev_ut-compas,github_token]
fr.insee.compas.github.token=VAULT[ut/compas/equipe/dev_ut-compas,github_api_token]



